<?= $this->doctype() ?>

<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Maestro Bet - Sua Jogada de Mestre!')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendName('description', 'Sua jogada de mestre.')
        ->appendName('google-site-verification', 'aWtmm_GHlpR8NKmc3yqrr6fEkF0Xv-tZJZ0E2gmkxIs')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('lib/bootstrap/css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('lib/font-awesome/css/all.css'))
        ->prependStylesheet($this->escapeHtml('https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css'))
    ?>
    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.4.1.min.js'))
    ?>
</head>

<body>
    <div class="home-animation animated fadeOut delay-4s">
        <img src="/img/logo-brasao.png" class="animated fadeIn slow ani-brasao" alt="Logo Brasao">
        <img src="/img/logo-maestro.png" class="animated fadeIn slow delay-1s ani-maestro" alt="Logo Titulo">
        <img src="/img/logo-texto.png" class="animated fadeIn slow delay-2s ani-texto" alt="Logo Texto">
    </div>

    <header class="main-menu animated fadeIn delay-5s slow">
        <?php
        $this->mainMenu()->setItems([
            [
                'id' => 'home',
                'label' => 'Home',
                'link' => $this->url('home')
            ],
            [
                'id' => 'sobre',
                'label' => 'Sobre',
                'link' => '#'
            ]
        ]);
        echo $this->mainMenu()->render();
        ?>
    </header>

    <div class="animated fadeIn delay-5s slow">
        <?= $this->content ?>
    </div>

    <footer class="footer animated fadeIn delay-5s slow">
        <a><i class="fab fa-facebook-square"></i></a>
        <a href="<?= $this->escapeHtml('https://www.instagram.com/maestrobet_oficial') ?>"><i class="fab fa-instagram"></i></a>
        <a><i class="fab fa-twitter-square"></i></a>
    </footer>
</body>

</html>