<?= $this->doctype() ?>

<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Maestro Bet - Sua Jogada de Mestre!')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendName('description', 'Maestro Bet - O guia da sua jogada de mestre!')
        ->appendName('google-site-verification', 'aWtmm_GHlpR8NKmc3yqrr6fEkF0Xv-tZJZ0E2gmkxIs')
        ->appendName('keywords', 'apostas esportivas, apostas, bet, bets, betting, sportbetting, odds, maestro, mestre, probabilidade, futebol, tênis')
        ->appendName('robots', 'index, follow')
        ->appendName('author', 'Maestro Bet')
        ->appendName('twitter:card', 'summary_large_image')
        ->appendProperty('og:title', 'Maestro Bet - Sua Jogada de Mestre!')
        ->appendProperty('og:description', 'Entenda como a Maestro Bet te ajuda a fazer sua jogada de mestre!')
        ->appendProperty('og:image', 'https://www.maestrobet.com.br/public/img/logo-square.png')
        ->appendProperty('og:url', 'https://www.maestrobet.com.br')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->appendAlternate(['rel' => 'apple-touch-icon', 'href' => $this->basePath() . '/img/apple-touch-icon.png'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('lib/bootstrap/css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('lib/font-awesome/css/all.css'))
        ->prependStylesheet($this->escapeHtml('https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css'))
    ?>
    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.4.1.min.js'))
    ?>
</head>

<body>
    <header class="main-menu">
        <?php
        $this->mainMenu()->setItems([
            [
                'id' => 'home',
                'label' => 'Home',
                'link' => $this->url('home')
            ],
            [
                'id' => 'sobre',
                'label' => 'Sobre',
                'link' => '#'
            ]
        ]);
        echo $this->mainMenu()->render();
        ?>
    </header>

    <?= $this->content ?>

    <footer class="footer">
        <a><i class="fab fa-facebook-square"></i></a>
        <a href="<?= $this->escapeHtml('https://www.instagram.com/maestrobet_oficial') ?>"><i class="fab fa-instagram"></i></a>
        <a><i class="fab fa-twitter-square"></i></a>
    </footer>
</body>

</html>