<?= $this->doctype() ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Maestro Bet - Sua Jogada de Mestre!')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('description', 'Sua jogada de mestre.')
            ->appendName('google-site-verification', 'aWtmm_GHlpR8NKmc3yqrr6fEkF0Xv-tZJZ0E2gmkxIs')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('lib/bootstrap/css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('lib/font-awesome/css/all.css'))
        ?>        
        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.4.1.min.js'))
        ?>
    </head>
    <body>
        <div class="main-menu">
            <?php
            $this->mainMenu()->setItems([
                [
                    'id' => 'home',
                    'label' => 'Home',
                    'link' => $this->url('home')
                ],
                [
                    'id' => 'sobre',
                    'label' => 'Sobre Nós',
                    'link' => $this->url('sobre')
                ]
            ]);
            echo $this->mainMenu()->render();
            ?>
        </div>
        <?= $this->content ?>
    </body>
</html>