<?php
$this->mainMenu()->setActiveItemId('home');
?>
<div class="container">
    <div class="row home-content text-center">        
        <div class="offset-sm-4 apresentacao">
            <img src="<?= $this->basePath('img/apresentacao.gif') ?>" alt="Apresentação">
        </div>
    </div>
    <div class="footer">
        <a><i class="fab fa-facebook-square"></i></a>
        <a href="<?= $this->escapeHtml('https://www.instagram.com/maestrobet_oficial') ?>"><i class="fab fa-instagram"></i></a>
        <a><i class="fab fa-twitter-square"></i></a>
    </div>
</div>