<?php
?>
<div class="container">
    <div class="row pt-4">
        <div class="offset-sm-2 col-sm-4 logo">
            <img src="/img/logo-branco.png" alt="">
        </div>
        <div class="col-sm-3 apresentacao">
            <img src="/img/apresentacao.gif" alt="Apresentação">
        </div>
    </div>
    <div class="footer">
        <a href="#"><i class="fab fa-facebook-square"></i></a>
        <a href="http://www.instagram.com/maestrobet_oficial"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-twitter-square"></i></a>
    </div>
</div>